[phases.setup]
nixPkgsExtra = ["python311", "gcc", "gnumake"]

[phases.install]
cmds = ["cd server && PYTHON=$(python3 -c 'import sys; print(sys.executable)') pnpm install"]

[phases.build]
cmds = []

[start]
cmd = "cd server && pnpm start"
